## This site is built using Poole + Hyde theme
## https://github.com/poole/hyde

# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

title:            Playbook
description:      ''
baseurl:          /mobix-playbook/
author:
  name:           'Mobix Software'
  url:            https://mobixsoftware.com

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mobixsoftware/mobix-playbook
